IDAM-433 Make organisations endpoint searchable
nice-digital/identity pull request #138
Opened 2022-01-04 17:59 UTC by imranazad

https://nicedigital.atlassian.net/browse/IDAM-433

2022-01-05 14:20 UTC, imranazad commented
@suegarner Could you please do the honours. Am I missing any unit / integration tests here?

2022-01-19 11:14 UTC, suegarner requested changes

2022-01-19 11:14 UTC, suegarner commented on NICE.Identity.Authorisation.WebAPI/DataModels/Organisation.cs
> +        public void UpdateFromApiModel(ApiModels.Organisation organisation, bool create)
If the migration script is changed to give a default DateAdded can we do away with the create flag?

2022-01-24 12:14 UTC, suegarner approved these changes

2022-01-24 12:39 UTC, merged